[project]
name = "relbench"
version = "0.0.1"


[tool.hatch.envs.default]
installer = "uv"
python = "3.12"
dependencies = [
  "ipykernel",
  "ipython",
  "relbench @ git+https://github.com/snap-stanford/relbench.git",
  "ruff",
  "shap",
  "tdqm",
  "pandas-stubs",
  "polars",
]
post-install-commands = [
  "uv pip install -e {root:parent:uri}/monorepo/src/python-api"
]

[tool.ruff]
line-length = 88
extend-include = ["*.ipynb"]
